[theme]
# Primary accent color for interactive elements.
primaryColor = "#A72037" 

# Background color for the main content area.
backgroundColor = "#E0E0E0"  

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#F8FAF9"

# Color used for almost all text.
textColor = "#333333"  

# Secondary text color for less emphasis.
secondaryTextColor = "#777777"  

# Color used for emphasis or highlights.
accentColor = "#A72037" 

# Font family for all text in the app, except code blocks.
font = "Roboto"
