[theme]
# Primary accent color for interactive elements.
primaryColor = "#00172B"

# Background color for the main content area.
backgroundColor = "#4A4B4C"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#2A2B2C"

# Color used for almost all text.
textColor = "#FFFFFF"

# Secondary text color for less emphasis.
secondaryTextColor = "#B0B0B0"

# Color used for emphasis or highlights.
accentColor = "#0078D4"

# Font family for all text in the app, except code blocks.
font = "sans serif"
